### PR TITLE
RDKBDEV-2828: fix line endings in printf strings

### PR DESCRIPTION
**Pull request by pradeeptakdas**
Reason for change:
A DOS line ending is \r\n. A Unix line ending is \n. The sequence \n\r is not a valid line ending on either system.

Test Procedure: Sanity.
Risks: None.

### CODE REVIEW

**Comment by pradeeptakdas** [comment]
Internal ticket for tracking https://ccp.sys.comcast.net/browse/RDKCOM-4966

**Review by karuna2git — CHANGES_REQUESTED** [review]
We are using linenoise library to print and that requires `\r` to be in there for rbuscli.
The sample providers and rbus/src can be updated.

**Comment by pradeeptakdas** [comment]
Hi @karuna2git 
As per @armcc input - if we we keeping \r it should be before \n. Adding \r after \n is in appropriate.
Can you please review the changes again and provide your input.

If you wish to keep \r before \n, we will make the necessary changes and will submit a new patch-set.

**Comment by pradeeptakdas** [comment]
Duplicate of https://github.com/rdkcentral/rbus/pull/224

**Pull request closed without merging**
